# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "jeffmccune/centos7"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "puppet" do |puppet|
    puppet.vm.network :private_network, ip: "192.168.11.3"
    puppet.vm.network :private_network, ip: "192.168.22.3"
    puppet.vm.network :private_network, ip: "172.16.33.3"
    puppet.vm.network :private_network, ip: "172.16.44.3"

    puppet.vm.hostname = "puppet"

    puppet.vm.synced_folder "../../", "/openstack"

    puppet.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] =  "1024"
        v.gui = true
    end
  end

  
  config.vm.define "control" do |control|
    control.vm.network :private_network, ip: "192.168.11.4"
    control.vm.network :private_network, ip: "192.168.22.4"
    control.vm.network :private_network, ip: "172.16.33.4"
    control.vm.network :private_network, ip: "172.16.44.4"

    control.vm.hostname = "control"

    control.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"]  = "1024"
        v.vmx["numvcpus"] = "1"
        v.gui = true
    end
  end

  
  config.vm.define "storage" do |storage|
    storage.vm.network :private_network, ip: "192.168.11.5"
    storage.vm.network :private_network, ip: "192.168.22.5"
    storage.vm.network :private_network, ip: "172.16.33.5"
    storage.vm.network :private_network, ip: "172.16.44.5"

    storage.vm.hostname = "storage"

    storage.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"]  = "1024"
        v.vmx["numvcpus"] = "1"
        v.gui = true
    end
  end

  
  config.vm.define "network" do |network|
    network.vm.network :private_network, ip: "192.168.11.6"
    network.vm.network :private_network, ip: "192.168.22.6"
    network.vm.network :private_network, ip: "172.16.33.6"
    network.vm.network :private_network, ip: "172.16.44.6"

    network.vm.hostname = "network"

    network.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"]  = "1024"
        v.vmx["numvcpus"] = "1"
        v.gui = true
    end
  end

  
  config.vm.define "compute" do |compute|
    compute.vm.network :private_network, ip: "192.168.11.7"
    compute.vm.network :private_network, ip: "192.168.22.7"
    compute.vm.network :private_network, ip: "172.16.33.7"
    compute.vm.network :private_network, ip: "172.16.44.7"

    compute.vm.hostname = "compute"

    compute.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"]  = "2048"
        v.vmx["numvcpus"] = "1"
        v.gui = true
    end
  end

  
end
